name: tflint
on:
  push:
  pull_request:
jobs:
  tflint:
    name: runner / tflint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - run: terraform init -chdir=./iac
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: "iac" # Optional. Change working directory
